### ISSUE TITLE
No module named 'sam2.build_sam' 

### ISSUE THREAD

**Issue by yincangshiwei** [neverbiasu/ComfyUI-SAM2#20]
Updating ComfyUI version to V2.50.3 resulted in a startup error for Sam2.
![image](https://github.com/user-attachments/assets/41215018-fde9-43a5-93dc-c5a51d46b012)

**Comment by rocing** [comment]
sam

**Comment by neverbiasu** [comment]
I'll check this soon.

**Comment by Summerbbk** [comment]
same problem

**Comment by subtera745** [comment]
I wonder if it's related to this?
https://github.com/facebookresearch/sam2/issues/172

**Comment by EmmanuelMr18** [comment]
Same problem here

**Comment by Philmar1986** [comment]
same problem. It worked yesterday, but today, it does not work.

**Comment by vojtajina** [comment]
I believe the issue is python is trying to load different `sam2` module. Likely there is a conflict with another ComfyUI package, for instance [ComfyUI_LayerStyle](https://github.com/chflame163/ComfyUI_LayerStyle/tree/main/py/sam2) also has `sam2` but without `build_sam`.

**Comment by vojtajina** [comment]
Here are some workarounds I can think of:
- if you can, delete the other package/nodes that has conflicting sam2
- rename `sam2` directory to something else like `local_sam2` but then you have to change all the imports inside because sam2 source code references itself through `sam2` rather than relative imports (not sure why)

**Comment by JohnsonXi** [comment]
If there is a folder with the same name sam2 under some packages in the python package search directory `sys.path`, python will search from front to back and import the first package sam2 first, which may be under ComfyUI_LayerStyle. In order to prioritize the search for packages under ComfyUI-SAM, through
```
# Get the absolute path of the directory where the current script is located
current_directory = os.path.dirname(os.path.abspath(__file__))
# Add the current directory to the first position of sys.path
if current_directory not in sys.path:
    sys.path.insert(0, current_directory)
```
Advance the priority. Import successful
